######################################################################
# Automatically generated by qmake (2.01a) Mon Dec 6 14:59:25 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ../sid.h ../state.h ../treemodel/treemodel.h ../treemodel/treeitem.h
SOURCES += main.cpp \
           ../sid.cpp \
           ../treemodel/treemodel.cpp \
           ../treemodel/treeitem.cpp
