######################################################################
# Automatically generated by qmake (2.01a) Wed Sep 29 15:07:46 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . 
INCLUDEPATH += . ../../ ../../qextserialport

# Input
HEADERS += ../../os5000.h ../../serialdevice.h ../../qextserialport/qextserialport.h ../../qextserialport/qextserialport_global.h
SOURCES += main.cpp ../../os5000.cpp ../../serialdevice.cpp ../../qextserialport/qextserialport.cpp ../../qextserialport/posix_qextserialport.cpp

