######################################################################
# Automatically generated by qmake (2.01a) Wed Apr 28 16:17:19 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . ../src/auv ../src/auv/qextserialport

# Input
HEADERS += game.h \
           ../src/auv/qextserialport/qextserialport.h \
           ../src/auv/qextserialport/qextserialport_global.h \
           ../src/auv/arduino.h \
           ../dashboard/controlboard/controlboard.h
FORMS += game.ui
SOURCES += game.cpp \
	   main.cpp \
	   ../src/auv/qextserialport/qextserialport.cpp \
	   ../src/auv/qextserialport/posix_qextserialport.cpp \
	   ../src/auv/arduino.cpp \
	   ../dashboard/controlboard/controlboard.cpp
