#!/bin/sh
## AUVC Start script
# make sure we're in the right dir
cd ~/auvc
echo "Launching Agent"
# Try to detect whether we are running on the AUV, and call ./agent -s if we are not
if !(hostname | grep auvt-auv > /dev/null); then
	if [ "$1" = "-b" ]; then 
		./agent -s 2> ./logs/run-`date +%F+%R`.log &
	else
		./agent -s
	fi
else
	# we should be on the AUV itself
	./agent 2> ./logs/run-`date +%F+%R`.log &
fi
echo -n "Starting Video Stream\n"
./startVideoStream
sleep 3
echo "System Initiated"
