######################################################################
# Automatically generated by qmake (2.01a) Sat Jul 3 12:26:47 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += cameratester.h qwebcam.h
FORMS += cameratester.ui
SOURCES += cameratester.cpp \
           main.cpp \
           qwebcam.cpp 
