#! /bin/bash
if test -n $1;then
echo -n $1
echo -n ": "
hg blame -u * 2> /dev/null | grep -i "^ *$1" | nl | tail -n1 | cut -f1
fi
if test -n $2;then
echo -n $2
echo -n ": "
hg blame -u * 2> /dev/null | grep -i "^ *$2" | nl | tail -n1 | cut -f1
fi
if test -n $3;then
echo -n $3
echo -n ": "
hg blame -u * 2> /dev/null | grep -i "^ *$3" | nl | tail -n1 | cut -f1
fi
if test -n $4;then
echo -n $4
echo -n ": "
hg blame -u * 2> /dev/null | grep -i "^ *$4" | nl | tail -n1 | cut -f1
fi
if test -n $5;then
echo -n $5
echo -n ": "
hg blame -u * 2> /dev/null | grep -i "^ *$5" | nl | tail -n1 | cut -f1
fi
if test -n $6;then
echo -n $6
echo -n ": "
hg blame -u * 2> /dev/null | grep -i "^ *$6" | nl | tail -n1 | cut -f1
fi
if test -n $7;then
echo -n $7
echo -n ": "
hg blame -u * 2> /dev/null | grep -i "^ *$7" | nl | tail -n1 | cut -f1
fi
if test -n $8;then
echo -n $8
echo -n ": "
hg blame -u * 2> /dev/null | grep -i "^ *$8" | nl | tail -n1 | cut -f1
fi
