######################################################################
# Automatically generated by qmake (2.01a) Fri Apr 23 20:00:24 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . ../../src/auv ../../src/auv/qextserialport

# Input
HEADERS += ../../src/auv/arduino.h \
		controlboard.h \
		../../src/auv/qextserialport/qextserialport.h \
		../../src/auv/qextserialport/qextserialport_global.h \
		../../src/auv/qextserialport/qextserialenumerator.h

SOURCES += main.cpp ../../src/auv/arduino.cpp \
		controlboard.cpp \
		../../src/auv/qextserialport/qextserialport.cpp \
		../../src/auv/qextserialport/posix_qextserialport.cpp \
		../../src/auv/qextserialport/qextserialenumerator_unix.cpp
